//
//  ViewModel.swift
//  MC04
//
//  Created by Laura C. Balbachan dos Santos on 27/03/24.
//

// Aqui é onde a comunicação entre as Views e o Model é feito, além de ser onde os dados são alterados

import Foundation
import SwiftData

struct ViewModel: Observable {
    
    var habits: [HabitTemplate] = [
        HabitTemplate(name: "Lavar o rosto", desc: "Essa tarefa é indicada ser realizada no período da manhã e da noite, pois além de limpar a pele, essa etapa remove a oleosidade, as impurezas vindas da poluição e as células mortas. Por isso, a higienização ajuda na desobstrução dos poros, previne o surgimento de cravos e espinhas e ainda dá mais viço ao rosto, deixando-o com uma aparência saudável.", steps: [["1","Lave suas mãos", "Antes de começar a lavar o rosto lave suas mãos. Assim você não corre perigo de contagiar seu rosto com possíveis bactérias."],["2", "Use água morna", "Cuidado com a temperatura da água, sempre tente lavar o rosto com uma água que esteja morna, pois água muito quente pode causar danos a pele."], ["3", "Use o sabonete correto e na medida certa", "De preferencia procure um dermatologista para ele analisar seu tipo de pele e o sabonete indicado para ela, é importante que utilize um sabonete especifico para o rosto. Se for sabonete liquido, apenas uma pequena porção do sabonete é o suficiente para lavar o rosto."], ["4", "Lave massageando o rosto ", "Não esfregue o rosto! Espalhe o sabonete em movimentos circulares fazendo uma massagem, pode ser usado uma esponja própria para usar no rosto. ", "Enxágue bem o rosto, pois deixar resíduos de sabonete pode causar irritações."], ["5", "Dica ", "Para higienizar a pele, você precisa escolher um sabonete que atenda às necessidades dela, dando exatamente o que ela precisa. "]], images: "sdv"),
        HabitTemplate(name: "Hidratação",  desc: "Hidratar a pele é essencial, pois ela fortalece a proteção da pele, prevenindo o ressecamento, os sinais de envelhecimento e diminui o risco de inflamações.\n Mesmo tendo uma pele oleosa usar hidratante é essencial. Mas tome cuidado e escolha um hidratante ideal para a sua pele com a ajuda de um dermatologista.", steps: [["1","Hidratante no rosto", "Após lavar o rosto passe o hidratante facial, fazendo movimentos circulares."],["2", "Hidratante no corpo", "Após o banho passe o hidratante corporal, dando atenção, principalmente, às regiões mais ressecadas."]], images: "sdv"),
        HabitTemplate(name: "Protetor solar",desc: "Extremamente importante, ajuda a combater o câncer de pele, evitar envelhecimento precoce, flacidez, lesões, entre outras complicações. \n Deve ser usado todos os dias até mesmo no inverno.\nUse um protetor que seja compatível com o que a sua pele", steps: [["1","Antes de aplicar", "Certifique-se de que a pele esteja seca e de preferencia limpa."],["2", "Aplique o protetor", "Aplique aproximadamente 1 (uma) colher de chá do protetor sobre rosto e pescoço."], ["3", "Espalhe", "Espalhe uniformemente certificando de cobrir todas as áreas expostas da pele."]], images: "sdv"),
        HabitTemplate(name: "Esfoliação", desc: "É uma limpeza profunda feita com gel ou creme com minúsculas partículas que desobstrui os poros, elimina as células mortas superficiais e evita pelos encravados devendo ser feita uma ou duas vezes por semana.", steps: [["1","Lavar", "Lave o rosto com um sabonete próprio para o rosto, de preferencia com água morna"],["2", "Aplicar", "Depois de lavar o rosto, com a pele ainda úmida, aplique o esfoliante na face com as mãos."], ["3", "Esfoliar", "Faça movimentos circulares suaves por toda a face, dando atenção para testa, nariz e área abaixo da boca, além da região da barba."], ["4", "Enxágue", "Enxágue bem o rosto com água em temperatura ambiente para remover o produto."], ["5", "Seque", "Use uma toalha limpa e macia e a passe no rosto com leveza para seca-lo. Evite esfregar, pois a pele do rosto é sensível."], ["6", "Finalize", "Finalize com um hidratante facial para acalmar a pele."]], images: "sdv"),
        HabitTemplate(name: "Unhas", desc: "Fazer as unhas é importante pois evita o acumulo de bactéria debaixo da unha, encravar, infecções, além de causar uma boa aparência e uma impressão de cuidado e higiene.", steps: [["1","Molhe as unhas", "Coloque um pouco de água morna em um recipiente e um pouco de sabão e coloque a parte da unhas submersos."],["2", "Limpe as unhas", "Agora que suas unhas estão úmidas, aproveite para limpá-las com uma escovinha dando atenção para a parte debaixo das unhas."], ["3", "Corte", "Com uma tesoura própria para isso, corte as unhas de forma arredondada. "], ["4", "Lixe", "Para dar um acabamento às pontas das unhas, lixe-as."], ["5", "Passe hidratante nas unhas", " "]], images: "sdv"),
        HabitTemplate(name: "Fazer a Barba", desc: "A barba é uma parte do corpo que requer uma atenção, tanto para quem mantem quanto para quem tira. Mante-la sempre bem feita é importante para manter uma aparência cuidada, sendo de extrema importância faze-la da forma correta para evitar danos a pele", steps: [["1","Lave o rosto", "Lavar o rosto com água morna ajuda a abrir os poros, permitindo que a lâmina passe mais facilmente pela pele deixando-a menos irritada. "],["2", "Aplique um gel ou espuma de barbear ", "Faça espuma e espalhe para ajudar a hidratar os pelos, melhorar o deslizamento da lâmina e ajudar a proteger contra irritação."], ["3", "Verifique se a lâmina está cega", "Se as fitas estiverem gastas ou  as lâminas cegas, talvez seja hora de trocar por um novo refil"], ["4", "Faça a barba no sentido do pelo e contra o pelo", "O pelo facial cresce em muitas direções, por isso você vai ter de raspar tanto no sentido de crescimento quanto contra. Lembrando sempre de tomar cuidado para não machucar a pele."], ["5", "Enxágue", "Enxágue bem todo rosto com água fria para acalmar a pele."], ["6", "Seque", "Use uma toalha limpa e macia e a passe no rosto com leveza para seca-lo."], ["6", "Enxágue", "Enxágue bem todo rosto com água fria para acalmar a pele."], ["7", "Hidrate", "Passe uma loção pós barba para manter sua pele bem hidratada."]], images: "sdv"),
        HabitTemplate(name: "Lavar a barba", desc: "Lavar a barba é essencial para mantê-la limpa e saudável, mas você deve evitar lavá-la em excesso. Lavar a barba várias vezes ao dias pode retirar os óleos naturais que a mantêm hidratada. O ideal é lavar a barba no máximo 2 vezes ao dia, usando um shampoo para barba suave e sem parabenos.", steps: [["1","Molhe a barba", "Molhe a barba com água de morna a fria (para não ressecar os fios!)"],["2", "Passe o shampoo", "Com os fios úmidos, coloque uma pequena porção do shampoo (especifico para barbas) nas mãos e passe na região da barba massageando com as pontas dos dedos."], ["3", "Enxágue", "Ainda com a água de morna a fria, retire todo o produto."], ["4", "Seque", "Use uma toalha limpa e macia e a passe na barba com leveza para seca-la."], ["5", "Dica:", " Para que sua barba tenha maior maleabilidade e redução da fricção entre os fios, é indicado que passa um condicionador (específico para barba) após o uso do shampoo."]], images: "sdv"),
        HabitTemplate(name: "Hidratacão capilar", desc: "A hidratação é um dos tratamentos mais importantes da rotina de cuidados com os cabelos. Ela deve ser feita com uma certa frequência para preservar a vitalidade dos fios. Além de repor umidade aos cabelos, o tratamento também é capaz de recuperar os principais nutrientes perdidos pela fibra capilar. Com a reposição nutritiva que a hidratação traz, os cabelos ficam mais resistentes e assumem um semblante mais saudável, livre de ressecamento e enfraquecimento capilar.", steps: [["1","Passe a máscara de hidratação", "Após lavar o cabelo com o Shampoo, ainda com os cabelos úmidos, passe com as pontas dos  dedos uma pequena quantidade da máscara de hidratação (adequada as características e necessidades do seu cabelo) do comprimento às pontas evitando encostar na raiz."],["2", "Espere", "Seguindo o tempo indicado no rótulo da máscara, espere que ela faça efeito (nessa parte pode ser usado uma touca térmica para fazer mais efeito)."], ["3", "Enxágue", "Após o tempo, tire totalmente o produto."], ["5", "Dica:", " A máscara de hidratação deve ser usada, pelo menos, uma vez por semana. Indicamos que converse com um profissional de confiança para definir uma frequência ideal para o seu tipo de fio."]], images: "sdv")
        
    ]
    
    let phrases: [String] = ["Se não quiser virar uma uva passa, comece a usar protetor solar!", "Se não quiser virar uma protetor solar, comece a usar uva passa!"]
    
  
    
}


